// example/nuxt-app/app/components/DevLogDemo.vue
<template>
  <div class="demo-container">
    <h1>Browser Echo Nuxt Demo</h1>
    <p>Open your server terminal to see browser logs!</p>
    
    <div class="button-group">
      <button @click="testConsoleLog">Test console.log</button>
      <button @click="testConsoleInfo">Test console.info</button>
      <button @click="testConsoleWarn">Test console.warn</button>
      <button @click="testConsoleError">Test console.error</button>
      <button @click="testConsoleDebug">Test console.debug</button>
      <button @click="testComplexObject">Test Complex Object</button>
      <button @click="testMultipleArgs">Test Multiple Arguments</button>
      <button @click="testBatchLogging">Test Batch Logging</button>
      <button @click="testNetworkRequests">Test Network Requests</button>
    </div>

    <div class="info">
      <p>Click the buttons above to generate different types of console output.</p>
      <p>The logs will appear in your server terminal with the [web] prefix.</p>
    </div>
  </div>
</template>

<script setup>
const testConsoleLog = () => {
  console.log('This is a regular console.log message from Nuxt app');
};

const testConsoleInfo = () => {
  console.info('This is an info message with useful information');
};

const testConsoleWarn = () => {
  console.warn('This is a warning message - something might be wrong');
};

const testConsoleError = () => {
  console.error('This is an error message - something went wrong!');
};

const testConsoleDebug = () => {
  console.debug('This is a debug message with detailed information');
};

const testComplexObject = () => {
  const complexObject = {
    user: {
      id: 123,
      name: 'John Doe',
      email: 'john@example.com',
      preferences: {
        theme: 'dark',
        language: 'en',
        notifications: true
      }
    },
    timestamp: new Date().toISOString(),
    metadata: {
      version: '1.0.0',
      environment: 'development'
    }
  };
  console.log('Complex object:', complexObject);
};

const testMultipleArgs = () => {
  console.log('Multiple', 'arguments', 'in', 'one', 'log', { key: 'value' }, [1, 2, 3]);
};

const testBatchLogging = () => {
  console.log('Batch log 1: Starting batch test');
  console.info('Batch log 2: Processing...');
  console.warn('Batch log 3: Almost done');
  console.log('Batch log 4: Batch complete');
  console.log('These logs might be batched together for efficiency');
};

const testNetworkRequests = async () => {
  console.log('🌐 Testing network requests...');

  try {
    // Test successful fetch
    await fetch('https://jsonplaceholder.typicode.com/posts/1');
    console.log('✅ Successful fetch completed');

    // Test POST request
    await fetch('https://jsonplaceholder.typicode.com/posts', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ title: 'Test', body: 'Test body' })
    });
    console.log('✅ POST request completed');

    // Test 404 error
    await fetch('https://jsonplaceholder.typicode.com/posts/999999');
    console.log('⚠️ 404 request completed');

  } catch (error) {
    console.error('🌐 Network test error:', error);
  }
};

// Log on component mount
console.log('DevLogDemo component mounted in Nuxt app');
</script>

<style scoped>
.demo-container {
  max-width: 800px;
  margin: 0 auto;
  padding: 2rem;
}

h1 {
  font-size: 2rem;
  margin-bottom: 1rem;
  color: #00dc82;
}

p {
  margin-bottom: 1rem;
  color: #666;
}

.button-group {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  margin: 2rem 0;
}

button {
  padding: 0.5rem 1rem;
  background-color: #00dc82;
  color: white;
  border: none;
  border-radius: 0.25rem;
  cursor: pointer;
  font-size: 0.875rem;
  transition: background-color 0.2s;
}

button:hover {
  background-color: #00a862;
}

.info {
  margin-top: 2rem;
  padding: 1rem;
  background-color: #f3f4f6;
  border-radius: 0.5rem;
}

.info p {
  margin: 0.5rem 0;
  font-size: 0.875rem;
}
</style>

// example/next-app/app/DevLogDemo.tsx
"use client";
import { useState } from "react";

export default function DevLogDemo() {
  const [count, setCount] = useState(0);

  const handleLogDemo = () => {
    console.log("📊 Regular log message from React component");
    console.warn("⚠️ Warning message with count:", count);
    console.error("❌ Error message for testing");
    console.info("ℹ️ Info message with object:", { count, timestamp: new Date() });

    try {
      throw new Error("Demo error with stack trace");
    } catch (error) {
      console.error("🔥 Caught error:", error);
    }
  };

  const handleAsyncError = async () => {
    console.log("🔄 Starting async operation...");

    try {
      await new Promise((_, reject) => {
        setTimeout(() => reject(new Error("Async operation failed")), 100);
      });
    } catch (error) {
      console.error("💥 Async error caught:", error);
    }
  };

  const handleNetworkTest = async () => {
    console.log("🌐 Testing network requests...");

    try {
      // Test successful fetch
      await fetch("https://jsonplaceholder.typicode.com/posts/1");
      console.log("✅ Successful fetch completed");

      // Test POST request
      await fetch("https://jsonplaceholder.typicode.com/posts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title: "Test", body: "Test body" })
      });
      console.log("✅ POST request completed");

      // Test 404 error
      await fetch("https://jsonplaceholder.typicode.com/posts/999999");
      console.log("⚠️ 404 request completed");

    } catch (error) {
      console.error("🌐 Network test error:", error);
    }
  };

  return (
    <div className="p-6 my-8 bg-gray-50 dark:bg-gray-900 rounded-lg">
      <h2 className="text-2xl font-bold mb-4">Browser Echo Demo</h2>
      <p className="mb-6">
        Open your terminal running <code className="bg-gray-200 dark:bg-gray-800 px-2 py-1 rounded">pnpm dev</code> to see logs streamed in
        real-time!
      </p>

      <div className="flex flex-wrap gap-4 mb-6">
        <button 
          onClick={handleLogDemo}
          className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 transition-colors"
        >
          Trigger Console Logs
        </button>

        <button 
          onClick={handleAsyncError}
          className="px-4 py-2 bg-red-500 text-white rounded hover:bg-red-600 transition-colors"
        >
          Test Async Error
        </button>

        <button 
          onClick={handleNetworkTest}
          className="px-4 py-2 bg-indigo-500 text-white rounded hover:bg-indigo-600 transition-colors"
        >
          Test Network Requests
        </button>

        <button
          onClick={() => {
            console.group("📂 Grouped logs");
            console.log("Message 1 in group");
            console.warn("Message 2 in group");
            console.error("Message 3 in group");
            console.groupEnd();
          }}
          className="px-4 py-2 bg-purple-500 text-white rounded hover:bg-purple-600 transition-colors"
        >
          Test Grouped Logs
        </button>
      </div>

      <div className="p-4 bg-white dark:bg-gray-800 rounded">
        <p className="mb-2">Count: {count}</p>
        <button
          onClick={() => {
            const newCount = count + 1;
            setCount(newCount);
            console.log(`🔢 Counter updated to: ${newCount}`);
          }}
          className="px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600 transition-colors"
        >
          Increment (+Log)
        </button>
      </div>
    </div>
  );
}
